version: 2

project_name: go-readme

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: go-readme
    main: ./cmd/go-readme
    binary: go-readme
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/sermachage/go-readme/cmd.Version={{.Version}}

archives:
  - id: go-readme
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
