name: 🐛 Bug Report
description: Report a reproducible bug in go-readme
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill in as much detail as possible so we can reproduce and fix it quickly.

  - type: input
    id: go-version
    attributes:
      label: Go version
      description: Output of `go version`
      placeholder: "go version go1.24.0 linux/amd64"
    validations:
      required: true

  - type: input
    id: go-readme-version
    attributes:
      label: go-readme version
      description: Output of `go-readme -version` or the git commit / tag you built from
      placeholder: "v0.1.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide the minimal steps to reproduce the behaviour.
      placeholder: |
        1. Run `go-readme -dir ./mypackage`
        2. Observe …
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: What actually happened? Include any error messages or unexpected output.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Paste relevant Go source snippets, generated README output, or any other context that may help.
