name: 🚀 Feature Request
description: Suggest a new feature or improvement for go-readme
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please be as specific as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What problem does this feature solve, or what need does it address?
      placeholder: "Currently go-readme does not support …"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the feature you would like to see. Include example CLI flags, template output, or API changes if applicable.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any workarounds or alternative approaches?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or examples that support this request.
